spring.application.name=restaurant


spring.data.mongodb.uri=mongodb://localhost:27017/restaurants
spring.data.mongodb.database=restaurants

openai.api.key= ${OPENAI_API_KEY:}
gemini.api.key=${GEMINI_API_KEY:}

# Optional: Enable debug logs
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

logging.level.org.springframework.web: DEBUG

management.endpoints.web.exposure.include=*
